"""add user table token col

Revision ID: 4b3708dd73c9
Revises: 492255b837dd
Create Date: 2020-12-07 19:43:43.031623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b3708dd73c9'
down_revision = '492255b837dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userr', sa.Column('token', sa.String(length=32), nullable=True))
    op.add_column('userr', sa.Column('token_expiration', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_userr_token'), 'userr', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_userr_token'), table_name='userr')
    op.drop_column('userr', 'token_expiration')
    op.drop_column('userr', 'token')
    # ### end Alembic commands ###
